#quartz:
#  enabled: true
#test:
#  error: true

server:
  servlet:
    context-path: /safeno

spring:
  application:
    name: safeno



#  #https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJDBCJobStoreClustering.html
#  quartz:
#    scheduler-name: safeno
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: never
#    wait-for-jobs-to-complete-on-shutdown: true
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceId: AUTO
#          jobStore:
#            isClustered: true
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            useProperties: true
#
#  datasource:
##    url: jdbc:h2:mem:test
#    url: jdbc:mysql://localhost:3306/safeno
#    username: root
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
##    defer-datasource-initialization: true
##
##  sql:
##    init:
##      mode: embedded
#
#safeno:
#  delete-time: 7d #duration
#  provider:
#    skt:
#      domain: https://safen.skbroadband.com:36361
#      delete-time: 3d
#      details:
#        group-code: autocrypt
#        customer-code: 1308
#    kt:
#      domain: unkown
#      delete-time: 4d
#    lg:
#      domain: unkown
#      delete-time: 5d
#  service:
#    taboso:
#      delete-time: 3d
#      provider: skt
#    move-free:
#      delete-time: 3d
#      provider: kt
#    imom:
#      delete-time: 3d
#      provider: lg
#    kcall:
#      delete-time: 1d
#      provider: skt
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#
##logging:
##  level:
##    org.hibernate.SQL: DEBUG
##    org.hibernate.orm.jdbc.bind: TRACE
##    org.hibernate.resource.transaction: DEBUG
##    org.springframework:
##      transaction: TRACE
##      jdbc.datasource.DataSourceTransactionManager: DEBUG
##      orm.jpa: TRACE

