spring:
  config:
    import:
      - classpath:properties/dev/datasource.yml
      - classpath:properties/dev/jpa.yml
      - classpath:properties/dev/logging.yml
      - classpath:properties/dev/quartz.yml
      - classpath:properties/dev/safeno.yml
