quartz.enabled: true
#quartz.enabled: false

spring:
  application:
    name: safeno

  h2:
    console:
      enabled: true

  #https://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/ConfigJDBCJobStoreClustering.html
  quartz:
    scheduler-name: safeno
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            isClustered: true
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true

  datasource:
#    url: jdbc:h2:mem:test
    url: jdbc:mysql://localhost:3306/safeno
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: embedded

safeno:
  delete-time: 7d #duration
  provider:
    skt:
      delete-time: 3d
    kt:
      delete-time: 4d
    lg:
      delete-time: 5d
  service:
    taboso:
      delete-time: 3d
    move-free:
      delete-time: 3d
    imom:
      delete-time: 3d

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.resource.transaction: DEBUG
#    org.springframework:
#      transaction: TRACE
#      jdbc.datasource.DataSourceTransactionManager: DEBUG
#      orm.jpa: TRACE

